hash: remove errors from api (breaking api change)
authzed/controller-idioms pull request #32
Opened 2023-01-19 23:54 UTC by ecordell

The hash interfaces returned errors before, but the underlying implementations picked for the hash package never return errors on calls to `Write`.

Bubbling the errors in the interface like this leads to a lot of unnecessary error handling, so it's worth breaking the api contract here (and we're pre-1.0.0 anyway).

Relevant functions:
https://github.com/cespare/xxhash/blob/fe2f6e86bb1d7041699efbe0fae02ec03ad063c8/xxhash.go#L59-L95
https://cs.opensource.google/go/go/+/refs/tags/go1.19.5:src/crypto/sha512/sha512.go;l=262-286
https://cs.opensource.google/go/go/+/refs/tags/go1.19.5:src/fmt/print.go;l=202-208

2023-01-20 23:59 UTC, jzelinskie requested changes

2023-01-20 23:59 UTC, jzelinskie commented on hash/hash.go
> +	// the error here tpp
Typo

2023-01-21 14:10 UTC, ecordell commented on hash/hash.go
> +	// the error here tpp
```suggestion
	// the error here too
```

2023-01-26 15:25 UTC, jzelinskie approved these changes

2023-01-26 16:22 UTC, merged